### PR TITLE
added a basic meaning function

### PR DESCRIPTION
**Pull request by ajax711**
wrote a horrible code for finding meaning of any word in or out of the dataset. please hide api keys

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Can you give the screenshots ?

**Comment by ajax711** [comment]
githubabuse

**Comment by 0x48piraj** [comment]
Test `meaning()` def. The code.

**Review by 0x48piraj — COMMENTED** [review]
Test `meaning()` def. The code.

> Add meaning("Any abusive word") to the end of script and run the script. Post the output.

**Comment by ajax711** [comment]
githubabuse2

**Comment by 0x48piraj** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
